-- ==========================================
-- MASTER DATABASE FIX FOR SAFERENT
-- RUN THIS IN YOUR SUPABASE SQL EDITOR
-- ==========================================

-- 1. Create Universities Table
create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique,
  short_name text,
  location text not null
);

-- 2. Create Properties Table (Complete definition)
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price numeric not null CHECK (price >= 0),
  category text not null,
  location text not null,
  image_url text not null,
  landlord_phone text not null,
  owner_id uuid references auth.users not null,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  verified boolean default false,
  university_id bigint references public.universities,
  description text,
  bedrooms int default 1,
  bathrooms int default 1,
  amenities text,
  is_featured boolean default false
);

CREATE INDEX IF NOT EXISTS idx_properties_featured_created ON public.properties (is_featured DESC, created_at DESC);

-- 3. Create Saved Properties Table
create table if not exists public.saved_properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  property_id bigint references public.properties not null,
  unique(user_id, property_id)
);

-- 4. Create Unlocked Listings Table
create table if not exists public.unlocked_listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  property_id bigint references public.properties not null,
  unique(user_id, property_id)
);

-- 5. Create Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text,
  phone_number text,
  university_id bigint references public.universities,
  role text check (role in ('student', 'landlord')),
  is_looking_for_roommate boolean default false,
  roommate_bio text,
  budget_range text
);

-- 6. Create Reviews Table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  property_id bigint references public.properties not null,
  user_id uuid references auth.users not null,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  unique(user_id, property_id)
);

-- 7. Create Admins Table
create table if not exists public.admins (
  id uuid references auth.users not null primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Enable RLS
alter table public.universities enable row level security;
alter table public.properties enable row level security;
alter table public.saved_properties enable row level security;
alter table public.unlocked_listings enable row level security;
alter table public.profiles enable row level security;
alter table public.admins enable row level security;
alter table public.reviews enable row level security;

-- 9. Policies for Reviews
drop policy if exists "Reviews are viewable by everyone." on public.reviews;
create policy "Reviews are viewable by everyone."
  on public.reviews for select
  using ( true );

drop policy if exists "Users can insert their own reviews." on public.reviews;
create policy "Users can insert their own reviews."
  on public.reviews for insert
  with check ( auth.uid() = user_id );

-- 10. Policies for Properties
drop policy if exists "Public properties are viewable by everyone." on public.properties;
create policy "Public properties are viewable by everyone."
  on public.properties for select
  using ( status = 'approved' );

drop policy if exists "Users can see their own properties." on public.properties;
create policy "Users can see their own properties."
  on public.properties for select
  using ( auth.uid() = owner_id );

drop policy if exists "Users can insert their own properties." on public.properties;
create policy "Users can insert their own properties."
  on public.properties for insert
  with check ( auth.uid() = owner_id );

drop policy if exists "Users can update their own properties." on public.properties;
create policy "Users can update their own properties."
  on public.properties for update
  using ( auth.uid() = owner_id );

insert into public.universities (name, short_name, location) values
  ('University of Ibadan', 'UI', 'Ibadan'),
  ('Lead City University', 'LCU', 'Ibadan'),
  ('The Polytechnic, Ibadan', 'Poly Ibadan', 'Ibadan'),
  ('Technical University', 'Tech-U', 'Ibadan'),
  ('Koladaisi University', 'KDU', 'Ibadan'),
  ('Precious Cornerstone University', 'PCU', 'Ibadan'),
  ('Dominion University', 'Dominion', 'Ibadan'),
  ('Emmanuel Alayande College of Education', 'EACOED', 'Oyo/Ibadan'),
  ('Federal College of Education (Special)', 'FCE Special', 'Oyo/Ibadan'),
  ('Federal School of Statistics', 'FSS Ibadan', 'Ibadan'),
  ('Federal Cooperative College', 'FCC Ibadan', 'Ibadan')
on conflict (name) do nothing;

-- 10. Trigger for Profiles
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'role');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- FINAL STEP: Mark all current properties as approved so they show up on landing page!
UPDATE public.properties SET status = 'approved' WHERE status = 'pending';
