-- Universities Table
create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null unique,
  short_name text,
  location text not null
);

-- Enable RLS for universities
alter table public.universities enable row level security;

-- Policies for universities (Public Read, Admin Write)
drop policy if exists "Universities are viewable by everyone." on public.universities;
create policy "Universities are viewable by everyone."
  on public.universities for select
  using ( true );

-- Seed Data (Ibadan Universities)
insert into public.universities (name, short_name, location) values
  ('University of Ibadan', 'UI', 'Ibadan'),
  ('Lead City University', 'LCU', 'Ibadan'),
  ('The Polytechnic, Ibadan', 'Poly Ibadan', 'Ibadan'),
  ('Technical University', 'Tech-U', 'Ibadan'),
  ('Dominican University', 'DU', 'Ibadan'),
  ('Kola Daisi University', 'KDU', 'Ibadan'),
  ('Precious Cornerstone University', 'PCU', 'Ibadan'),
  ('Ajayi Crowther University', 'ACU', 'Oyo/Ibadan')
on conflict (name) do nothing;

-- Properties Table (Updated with University Foreign Key)
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price numeric not null CHECK (price >= 0),
  category text not null,
  location text not null,
  image_url text not null,
  landlord_phone text not null,
  owner_id uuid references auth.users not null,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  verified boolean default false,
  university_id bigint references public.universities -- NEW COLUMN
);

-- Admins Table
create table if not exists public.admins (
  id uuid references auth.users not null primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.properties enable row level security;
alter table public.admins enable row level security;

-- Policies for Admins
create policy "Admins can see everything"
  on public.admins for select
  using ( auth.uid() = id );

-- UPDATED Policies for properties
drop policy if exists "Public properties are viewable by everyone." on public.properties;
create policy "Public properties are viewable by everyone."
  on public.properties for select
  using ( status = 'approved' ); 

drop policy if exists "Admins can see all properties" on public.properties;
create policy "Admins can see all properties"
  on public.properties for select
  using ( exists (select 1 from public.admins where id = auth.uid()) );

drop policy if exists "Admins can update properties" on public.properties;
create policy "Admins can update properties"
  on public.properties for update
  using ( exists (select 1 from public.admins where id = auth.uid()) );

drop policy if exists "Users can insert their own properties." on public.properties;
create policy "Users can insert their own properties."
  on public.properties for insert
  with check ( auth.uid() = owner_id );

drop policy if exists "Users can see their own properties." on public.properties;
create policy "Users can see their own properties."
  on public.properties for select
  using ( auth.uid() = owner_id );

drop policy if exists "Users can update their own properties." on public.properties;
create policy "Users can update their own properties."
  on public.properties for update
  using ( auth.uid() = owner_id );

drop policy if exists "Users can delete their own properties." on public.properties;
create policy "Users can delete their own properties."
  on public.properties for delete
  using ( auth.uid() = owner_id );

-- Unlocked Listings (No change)
create table if not exists public.unlocked_listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  property_id bigint references public.properties not null,
  unique(user_id, property_id)
);

alter table public.unlocked_listings enable row level security;

drop policy if exists "Users can see their own unlocked listings." on public.unlocked_listings;
create policy "Users can see their own unlocked listings."
  on public.unlocked_listings for select
  using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own unlocked records." on public.unlocked_listings;
create policy "Users can insert their own unlocked records."
  on public.unlocked_listings for insert
  with check ( auth.uid() = user_id );

-- Storage Policies
insert into storage.buckets (id, name, public)
values ('property-images', 'property-images', true)
on conflict (id) do nothing;
