-- Saved Properties Table
create table if not exists public.saved_properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  property_id bigint references public.properties not null,
  unique(user_id, property_id)
);

-- RLS
alter table public.saved_properties enable row level security;

create policy "Users can see their own saved properties"
  on public.saved_properties for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own saved properties"
  on public.saved_properties for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own saved properties"
  on public.saved_properties for delete
  using ( auth.uid() = user_id );
